### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read finished A: tlsv1 alert internal error

### ISSUE THREAD

**Issue by bennettl** [nomad/houston#129]
When trying to send the push notification I'm getting this. I made sure the device token and .pem file are valid.

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read finished A: tlsv1 alert internal error
	from /Library/Ruby/Gems/2.0.0/gems/houston-2.2.3/lib/houston/connection.rb:44:in `connect'
	from /Library/Ruby/Gems/2.0.0/gems/houston-2.2.3/lib/houston/connection.rb:44:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/houston-2.2.3/lib/houston/connection.rb:19:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/houston-2.2.3/lib/houston/client.rb:40:in `push'
```

**Comment by elementsrtyte** [comment]
Just started receiving this error as well :(

**Comment by bennettl** [comment]
I resolved the issue myself, turns out I shouldn't export both the cert and the private key into .p12, only the cert.

```
1. Click the disclosure arrow next to your certificate in Keychain Access and select the certificate and the key.
2. Right click and choose Export 2 items….
3. Choose the p12 format from the drop down and name it cert.p12.
```

For instruction #2, I only exported 1 item.
